name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  call-reusable-workflow:
    uses: ddt-mmt/pipo/.github/workflows/reusable_ci.yml@master # Ganti 'ddt-mmt/pipo' dengan 'username_anda/nama_repo_pipo'
    with:
      python-version: '3.x'
      docker-image-name: 'sooperbot/projek-migrasi'
      push-docker-image: true
    secrets:
      DOCKER_USERNAME: ${ secrets.DOCKER_USERNAME }
      DOCKER_PASSWORD: ${ secrets.DOCKER_PASSWORD }
